[tools]
node = "22.21.1"
npm = "11.11.0"
"npm:opencode-ai" = "1.1.63"
"npm:@devcontainers/cli" = "0.83.2"
"npm:eas-cli" = "16.32.0"
"aqua:ast-grep/ast-grep" = "0.41.0"
"aqua:pnpm" = "10.30.1"

[settings]
lockfile = true
